version: '2'
services:
    gestionemployes-app:
        image: gestionemployes
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gestionemployes-mysql:3306/gestionemployes?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gestionemployes-mysql:
        extends:
            file: mysql.yml
            service: gestionemployes-mysql
